module.exports = {
	TOOLS: '🛠️',
	SMALL_BLUE_DIAMOND: '🔹',
	SMALL_ORANGE_DIAMOND: '🔸',
	SMALL_WHITE_SQUARE: '▫️',
	UP_TRIANGLE: '🔺',
	SPEAKING_HEAD: '🗣️',
	LOUD_SPEAKER: '📢',
	EXCLAMATION: '❗',
	BANGBANG: '‼️',
	DICE: '🎲',
	WWW: '🌐',
	ARROW_SHADED_RIGHT: '➩',
	ARROW_LEFT: '⬅',
	ARROW_RIGHT: '➡',
	PLAY: '▶',
	CROSS: '❌',
	WARNING: '⚠️',
	WAVY_DASH: '〰️',
	ALARM: '⏰',
	CLOCK_3: '🕒',
	HEADPHONES: '🎧',
	CD: '💿',
	MUSIC_NOTE: '🎵',
	MUSIC_NOTES: '🎶',
	MUSIC_8TH: '♪',
};
