module.exports = {
	LOG_TYPE: {
		VERBOSE: 'VERBOSE',
		ERROR: 'ERROR',
	},
	RECITAL: {
		SHOULD_NOT_END: 'SHOULD_NOT_END',
		END_AND_DELETE_ALL_MESSAGES: 'END_AND_DELETE_ALL_MESSAGE',
		END_AND_REMOVE_ONLY_REACTIONS: 'END_AND_REMOVE_ONLY_REACTIONS',
	},
	MUSIC_TYPE: {
		YOUTUBE: 'YOUTUBE',
	},
	PLAYER_STATE: {
		INIT: 'INIT',
		PLAYING: 'PLAYING',
		PAUSED: 'PAUSED',
		STOPPED: 'STOPPED',
	},
	ACTIVITY: {
		PLAYING: 'PLAYING',
		STREAMING: 'STREAMING',
		LISTENING: 'LISTENING',
		WATCHING: 'WATCHING',
	},
};
